{{- if .Values.configFiles.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "harbor-day2-operator.fullname" . }}-config
  labels:
    {{- include "harbor-day2-operator.labels" . | nindent 4 }}
data:
  {{- range $filename, $content := .Values.configFiles }}
  {{- if ne $filename "enabled" }}
  {{ $filename }}: |
    {{- $content | nindent 4 }}
  {{- end }}
  {{- end }}
{{- end }}
