{{- if .Values.harbor.robotSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "harbor-day2-operator.fullname" . }}-robot
  labels:
    {{- include "harbor-day2-operator.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $value := .Values.harbor.robotSecrets }}
  {{ $key }}: {{ $value | b64enc }}
  {{- end }}
{{- end }}
---
{{- if and .Values.oidc.enabled (ne .Values.oidc.staticClientToken "changeme") }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "harbor-day2-operator.fullname" . }}-oidc
  labels:
    {{- include "harbor-day2-operator.labels" . | nindent 4 }}
type: Opaque
data:
  OIDC_STATIC_CLIENT_TOKEN: {{ .Values.oidc.staticClientToken | b64enc }}
{{- end }}
