apiVersion: v1
kind: Secret
metadata:
  name: {{ include "harbor-day2-operator.fullname" . }}-admin
  labels:
    {{- include "harbor-day2-operator.labels" . | nindent 4 }}
type: Opaque
data:
  password-new: {{ required "A new admin password is required" .Values.harbor.adminPasswordNew | b64enc }}
  {{- if .Values.harbor.adminPasswordOld }}
  password-old: {{ .Values.harbor.adminPasswordOld | b64enc }}
  {{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "harbor-day2-operator.fullname" . }}-robot
  labels:
    {{- include "harbor-day2-operator.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $value := .Values.harbor.robotSecrets }}
  {{ $key }}: {{ $value | b64enc }}
  {{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "harbor-day2-operator.fullname" . }}-oidc
  labels:
    {{- include "harbor-day2-operator.labels" . | nindent 4 }}
type: Opaque
data:
  OIDC_STATIC_CLIENT_TOKEN: {{ required "An OIDC static client token is required" .Values.oidc.staticClientToken | b64enc }}
